name: Deploy Cloudflare Worker (Production)

on:
  push:
    branches: [main, master]
env:
  CLOUDFLARE_WORKERS_NAME: docs-apiseven-com-production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name ${{ env.CLOUDFLARE_WORKERS_NAME }}
        continue-on-error: false
